### ISSUE TITLE
Отсутствие необходимого исключения при создании кредитного счета с отрицательным балансом

### ISSUE THREAD

**Issue by 0ldBread** [0ldBread/TeamProject#23]
# Описание
При реализации кода упущено исключение, когда создается кредитный счет с отрицательным балансом

# Локация дефекта
https://github.com/0ldBread/TeamProject/blob/0b4e3680ee2ade70c0d2a4fa0a7383e5cd226767/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/0ldBread/TeamProject/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java)
2. Создать объект класса CreditAccount с начальным балансом -1000, кредитным лимитом 5000, кредитной ставкой 15
3. Запустить тест
4. Посмотреть на вывод консоли
 
*Ожидаемый результат*  Вывод сообщения - тест пройден успешно
*Фактический результат* Вывод сообщения - Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown

# Скриншот

![image](https://github.com/0ldBread/TeamProject/assets/102696126/b8e90de4-1b56-4642-9795-97cec0be830e)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MuratOralbaev** [comment]
Исключение добавлено
